package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.InstructedCar;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface InstructedCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTED_CAR
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    int insert(InstructedCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTED_CAR
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    List<InstructedCar> selectAll();
}