package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Part;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    int insert(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    Part selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    List<Part> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    int updateByPrimaryKey(Part record);

    Part findByName(String name);
}