package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.PartCar;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PartCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART_CAR
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    int insert(PartCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART_CAR
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    List<PartCar> selectAll();
}