package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Part;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    int insert(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    Part selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    List<Part> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    int updateByPrimaryKey(Part record);
}