package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.TITLE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.PRICE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private Integer price;

    private List<Part> parts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.TITLE
     *
     * @return the value of PUBLIC.CAR.TITLE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.TITLE
     *
     * @param title the value for PUBLIC.CAR.TITLE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @return the value of PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @param ownerId the value for PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.PRICE
     *
     * @return the value of PUBLIC.CAR.PRICE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.PRICE
     *
     * @param price the value for PUBLIC.CAR.PRICE
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}