package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PartCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART_CAR.PART_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private Integer partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART_CAR.CAR_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    private Integer carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART_CAR.PART_ID
     *
     * @return the value of PUBLIC.PART_CAR.PART_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public Integer getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART_CAR.PART_ID
     *
     * @param partId the value for PUBLIC.PART_CAR.PART_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setPartId(Integer partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART_CAR.CAR_ID
     *
     * @return the value of PUBLIC.PART_CAR.CAR_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART_CAR.CAR_ID
     *
     * @param carId the value for PUBLIC.PART_CAR.CAR_ID
     *
     * @mbg.generated Sun May 08 13:33:14 EEST 2022
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}