package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Part {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.ID
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.NAME
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.ID
     *
     * @return the value of PUBLIC.PART.ID
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.ID
     *
     * @param id the value for PUBLIC.PART.ID
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.NAME
     *
     * @return the value of PUBLIC.PART.NAME
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.NAME
     *
     * @param name the value for PUBLIC.PART.NAME
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Car> cars;
}